name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: false

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: >
        micromamba create --name TEST python=${{ matrix.python-version }} --file reqs/base.yml --channel conda-forge
        && micromamba install --name TEST --file reqs/dev.yml --channel conda-forge
        && micromamba activate TEST
        && python -m pip install -e . --no-deps --force-reinstall

    - name: Tests
      shell: bash -l {0}
      run: >
        micromamba activate TEST
        && python -m pytest tests
